[platforms.armv7-apple-ios]
rustc_triple="armv7-apple-ios"

[platforms.armv7s-apple]
rustc_triple="armv7s-apple-ios"

[platforms.aarch64-apple-ios]
rustc_triple="aarch64-apple-ios"

[platforms.i386-apple-ios]
rustc_triple="i386-apple-ios"

[platforms.x86_64-apple-ios]
rustc_triple="x86_64-apple-ios"
