[package]
name = "gazetteer-entity-parser"
version = "0.2.0"
authors = ["Alaa Saade <alaa.saade@snips.ai>"]

[profile.bench]
debug = true

[dependencies]
failure = "0.1"
serde_json = "1.0.21"
serde_derive = "1.0.66"
serde = "1.0.66"
rmp-serde = "0.13.7"
fnv = "1.0.6"

[dev-dependencies]
criterion = "0.2"
rand = "0.5"
tempfile = "3.0.2"
mio_httpc = {version = "0.6", features = ["rtls"]}

[[bench]]
name = "bench_parser"
harness = false
