[package]
name = "nr_builtin_resolver"
version = "0.1.0"
authors = ["Alaa Saade <alaa.saade@snips.ai>"]

[dependencies]
snips-fst = { git = "ssh://git@github.com/snipsco/snips-fst-rs", rev = "52208051da5ed8832a74e77955d0f8235405a931" }
failure = "0.1"
serde_json = "1.0.21"
serde_derive = "1.0.66"
serde = "1.0.66"

[dev-dependencies]
criterion = "0.2"
rand = "0.5"

[[bench]]
name = "bench_resolver"
harness = false
